### ISSUE TITLE
Drag'n drop .sf2 file doesn't works in Reaper

### ISSUE THREAD

**Issue by brunetton** [brummer10/Fluida.lv2#13]
Hi

I'd love to be able to drag'n drop soundfont file onto Fluida (to be able to use my favorite file browser, that is definitively not build-in Fluida one ;))

Do you plan to add this ? I'd find this VERY useful ! 

Thanks

**Comment by brummer10** [comment]
Hi
It is supported. 
![Peek 2022-03-25 06-09](https://user-images.githubusercontent.com/2683982/160058564-65ef2a3a-9034-4584-88a4-9bfb62a8744b.gif)

Just some hosts may not forward the drag data to the plugin UI, then it didn't work.

**Comment by brunetton** [comment]
Thanks a lot.

Unfortunately in my case (using Reaper 6.52) this gives me this error message:

![image](https://user-images.githubusercontent.com/86322/160606969-bbca7441-064c-4217-8edb-fd20781bd607.png)

I do not know howto have more information. Nothing in console logs when running Reaper from console. 

I only trued in Reaper at first. Then I tried in Carla and **it works in Carla**; so it seems to be a problem related to Reaper. Can you have a look ?

Thanks a lot !

**Comment by brunetton** [comment]
Thanks.
So I contacted them: https://forum.cockos.com/showthread.php?p=2545643#post2545643

Let's see
