### ISSUE TITLE
Build error on Pop!_OS 22.04

### ISSUE THREAD

**Issue by hijinio** [brummer10/Fluida.lv2#14]
Hi there - I installed the dependencies, but when I compile, I run across this error related to xwidgets.h, but I can't find any dev files to resolve. Thoughts about how to address? Thanks!

$ make
g++ -std=c++11  -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -funroll-loops -fstack-protector -ffast-math -fomit-frame-pointer -fstrength-reduce `pkg-config --cflags --libs fluidsynth` -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--exclude-libs,ALL -msse3 -mfpmath=sse -mfxsr fluida.cpp XSynth.cpp -I.  -lm -pthread -lpthread -shared -lm -Wl,-z,noexecstack -Wl,--no-undefined -fvisibility=hidden `pkg-config --cflags --libs fluidsynth` -o Fluida.so
cc -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -funroll-loops -fstack-protector -ffast-math -fomit-frame-pointer -fstrength-reduce `pkg-config --cflags --libs fluidsynth` -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--exclude-libs,ALL -msse3 -mfpmath=sse -mfxsr -Wl,-z,nodelete fluida_ui.c -I../libxputty/libxputty/include/ -Wl,-z,noexecstack -Wl,--no-undefined -fvisibility=hidden -L. ../libxputty/libxputty/libxputty.a -shared `pkg-config --cflags --libs cairo x11` -lm -o Fluida_ui.so
In file included from lv2_plugin.cc:22,
                 from fluida_ui.c:46:
lv2_plugin.h:26:10: fatal error: xwidgets.h: No such file or directory
   26 | #include "xwidgets.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:107: Fluida] Error 1

**Comment by brummer10** [comment]
That looks as if libxputty isn't build before. Note, you must run make from the top level directory in order to build libxputty first. 
libxputty is a static lib which is included in the source.

**Comment by brummer10** [comment]
> $ ls -a
> . .. Fluida Fluida.png .github .gitignore .gitmodules libxputty LICENSE Makefile README.md

That looks strange. 
There must be a directory .git as well.
Maybe try a new checkout from git. 
Note, when you use the tarball from the release page, you must use this one [Fluida_0.7.tar.gz](https://github.com/brummer10/Fluida.lv2/files/6329806/Fluida_0.7.tar.gz) as only this contain the needed git structure to build the submodule. (That is a known issue with github and submodule).
Still I recommend to use a git checkout, as some bugfixes been not released now, but been in the development version already.

**Comment by brummer10** [comment]
Close this issue now a no more information arrived.
