### ISSUE TITLE
`makeResident` makes no GUI in JUCE hosts

### ISSUE THREAD

**Issue by KottV** [brummer10/Fluida.lv2#16]
Hi,

According this post https://forum.juce.com/t/lv2-issues/52412/21 `makeResident` is unsupported feature, thus Fluida.lv2 (as some other Gx plugins) won't show in JUCE LV2 hosts.

Simple removing of `lv2:requiredFeature guiext:makeResident;` line from the `Fluida.ttl` fixes the issue, also it passes `lv2lint` and works with `jalv`.

**Comment by brummer10** [comment]
Hi
Thanks for the hint, I've completely forgotten to remove this. Done now.

**Comment by KottV** [comment]
Great, it works now, thank You!
I think Gx bundle worth update too: https://github.com/brummer10/GxPlugins.lv2 these plugins have same problem, but as I can see removing `makeResident` is not enough. For example, I had to change the `gx_voodoo.ttl` to make it work in JUCE:
```
...
<http://guitarix.sourceforge.net/plugins/gx_voodoo_gui#_voodoo_>
  a guiext:X11UI;
  guiext:binary <gx_voodoo_ui.so>;
        lv2:extensionData guiext::idle ;
        lv2:extensionData guiext:resize ;
        lv2:extensionData guiext:idleInterface ;
        lv2:optionalFeature guiext:idleInterface ;
```

not sure that it's a correct hough.

**Comment by brummer10** [comment]
So I've updated the GxPlugins as well now, they should work now in your juce host.
