### ISSUE TITLE
Instrument choice is not kept when plugin is reloaded in DAW (ardour, reaper)

### ISSUE THREAD

**Issue by sebageek** [brummer10/Fluida.lv2#21]
I've loaded up Fluida.lv2 in ardour and reaper, chose an instrument (that is not the first instrument in the sf2). When saving the project, closing the DAW, reopening the DAW and then reloading the project the instrument choice of all Fluida.lv2 instances is set back to the first instrument.

In reaper this also happens to all Fluida.lv2 instances when the project is rendered to a soundfile, meaning only the first instrument can be used in the output format (but as this is a closed source app...).

Any idea what could be causing this?

**Comment by brummer10** [comment]
Yes, the current instrument wasn't part of the state file. I've added that now. 
Should work now with new saved sessions.

**Comment by sebageek** [comment]
Cool, seems to work now.
