### ISSUE TITLE
File selector suggestions

### ISSUE THREAD

**Issue by danboid** [brummer10/Fluida.lv2#22]
I'd like to see the fluida file selector get a few tweaks:

* There doesn't currently seem to be a way to quickly jump to and browse the parent directory, either being able to click on a double dot icon or an up icon next to the path dialog.

* If the places column is going to remain as-is, please add /usr/share/sounds/sf2 as one of the default paths as this is where Debian and Ubuntu store their soundfonts.

* I'd rather see places replaced by a list of bookmarked paths. Users would be able to drag n' drop dirs into that column for quick access to specific paths. 

* It would be nice if the path dialog was editable so paths could be entered manually instead of having to use the mouse to browse to them.

**Comment by brummer10** [comment]
Hi
Thanks for the Suggestion. I'll think about If or how I could include them. To Point one, you could Go to the parent directory with the mousewheel or do a right click on the address, that will Pop Up a Menu with the parent directorys.

**Comment by danboid** [comment]
Thanks for considering my suggestions Hermann! I've not made proper use of it yet but this is a very useful and easy to use and install plugin.

**Comment by danboid** [comment]
I've not been able to work out where fluida/Cairo gets its list of Places (paths) to show in the file open window so as a workaroud until this gets fixed I've created a symbolic link from /usr/share/sounds/sf2 to ~/sf2 .

**Comment by brummer10** [comment]
The Places comes from `xdg-user-dirs`.
Check your  ./config/user-dirs.dirs file. 
You could add/remove places there, most (I guess all) file-managers will use this file to generate the places list.

**Comment by danboid** [comment]
I tried adding the line:

```
XDG_SF2_DIR="/usr/share/sounds/sf2"
```
to ~/.config/user-dirs.dirs like so:

```
dan@zbook:~/.config$ cat user-dirs.dirs 
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
XDG_SF2_DIR="/usr/share/sounds/sf2"
```

but now qtractor crashes as soon as I click on the folder icon in fluida to try to open a soundfont.

```
$ qtractor 
Gtk-Message: 13:54:56.192: Failed to load module "canberra-gtk-module"

(qtractor:2350): GLib-GObject-WARNING **: 13:54:56.207: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-application-prefer-dark-theme'

(qtractor:2350): GLib-GObject-WARNING **: 13:54:56.208: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-application-prefer-dark-theme'
Segmentation fault
```

**Comment by danboid** [comment]
I've also tried

```
XDG_MUSIC_DIR="/usr/share/sounds/sf2"
```

but again qtractor segfaults at the same point, clicking on the folder icon.

**Comment by brummer10** [comment]
Oh, yes, there was a bug in the xdg_user_dir parser. I've fixed that now. 
It should work now with both options you've tried.

**Comment by danboid** [comment]
Hi @brummer10 

Yes, thats fixed now.

It would be good if you could edit the Fluida README to explain how users can edit `./config/user-dirs.dirs` to add custom entries to the open file window. That file was unknown to me until you told me about it.

**Comment by brummer10** [comment]
I could do that, but, that is more about the general XDG standard given by freedesktop.org and not really related to Fluida.lv2.

**Comment by danboid** [comment]
I think you should. I did search for this info before I asked you but failed to find it.

It will only take a couple of sentences to do and this makes fluida much more usable for me. I'll submit a PR to add it if you want?

**Comment by danboid** [comment]
https://github.com/brummer10/Fluida.lv2/pull/24

**Comment by danboid** [comment]
I should note that I had tried creating a bookmark to my sf2 dir using MATE's Caja file manager but, surprisingly, it doesn't seem to use the user-dirs.dirs file because my bookmarked dirs didn't appear in the Places panel of Fluida's file selector.

**Comment by brummer10** [comment]
Thanks a lot. Merged.

**Comment by danboid** [comment]
I'm going to close this now as knowing how to configure the XDG user dirs fixes most of my previous issues with the file selector.

**Comment by danboid** [comment]
Just to correct myself on Caja and dirs of interest. Caja does acknowledge the XDG user dirs, its just that you can't add or remove them from within Caja and its Bookmarked dirs, which you can add and remove at will using the Caja GUI are treated separately.

**Comment by brummer10** [comment]
Yes, bookmarks been a different thing. Apps usually using there own config file to store bookmarks as, in opposite to the XDG user dirs,  they don't been meant to be global. 
Fluida can't use bookmarks because it didn't have a config file. So the only way to add a "bookmark" is to add it to the XDG user dirs.
