### ISSUE TITLE
Instruments from MSB 001 onwards are not playable.

### ISSUE THREAD

**Issue by juancarlangas** [brummer10/Fluida.lv2#23]
Let's take as a known example the soundfont GSM-V2.01.sf2, which contains:

**- from 000 000 Piano 1 --> 000 127 Gun Shot."**

Next we have

**- 001 008 Pop Celesta --> 128 064 --SGM Drum Kits--**

When we select any sound from this second group, **no sound is heard.**

![imagen](https://user-images.githubusercontent.com/72962922/236056732-c9e64be8-6304-4c04-b44d-eb1bcef46315.png)

**Comment by brummer10** [comment]
Hi
Thanks for reporting the issue. I've pushed a fix for it to the repository. Let me know if it works now as expected.

**Comment by juancarlangas** [comment]
Thank you very much. It works awesome!!!! Very happy with collaborate you and also because it's my first GitHub collaborating issue post.

Be sure I will be in contact since i think Fluida.lv2 will be my selection for huge music creation.

Congratulations!!

**Comment by brummer10** [comment]
Ah, I see. Latest commit should fix that as well now.

**Comment by juancarlangas** [comment]
Congratulations. The program now works perfectly for my use. However, I think the plugin still has unexpected behavior:

So far, if I adjust my musical notes to **channel 10** and assign an instrument in Fluida.lv2, when I restart the session/DAW, **it goes back to not playing any sound**. Could you perform this test? For now, I have to travel and can't do any further testing, but I'll continue to investigate this. If you prefer, I can open a new issue or continue with this one.

**Comment by brummer10** [comment]
Yes. I've forgotten to save the channel in the state file, done now. Should be fixed now.
Enjoy your journey.
