### ISSUE TITLE
Fluida won't load instruments

### ISSUE THREAD

**Issue by funkaloss** [brummer10/Fluida.lv2#25]
Hi!

I'm trying to use Reaper 6.83 and Fluida on my Lubuntu 23.10 machine.

Fluida won't load any of the .sf2 instruments I've tried. When I select a file and click Load it takes me back to the main GUI without anything loaded. It still says None.

Thanks in advance!

**Comment by brummer10** [comment]
Hi
Do you tried with the latest git version from the repository? There are a couple of bugs fixed since the latest release.

regards
hermann

**Comment by funkaloss** [comment]
Hi!
I downloaded the pre-compiled binary from GitHub yesterday.

//Jonas


Den sön 22 okt. 2023 kl 10:09 skrev Hermann ***@***.***>:

**Comment by brummer10** [comment]
Yep, I need to make a new release to update the binary. Gime a day.

**Comment by funkaloss** [comment]
Absolutely.

Den sön 22 okt. 2023 11:18Hermann ***@***.***> skrev:

**Comment by funkaloss** [comment]
I installed the dependencies and now it works fine.

I'm new to Linux.

Thank you!
//Jonas

Den sön 22 okt. 2023 11:19Jonas Nilsson ***@***.***> skrev:

**Comment by brummer10** [comment]
I've forgotten that the binary represent anyway the latest git status and not the latest release. So I close this issue now as it is solved.
