### ISSUE TITLE
UI does not scale correctly

### ISSUE THREAD

**Issue by ghost** [brummer10/Fluida.lv2#29]
Tested on Linux Mint 21.3 (Cinnamon desktop), Reaper 7.07, Fluida 0.9.2.

The UI is not scaled correctly. Specifically, 
1) The piano roll and SF2 file path font size do not scale correctly with the rest of the UI.
2) The preset drop down list in case of multi-instrument SF2s and the popup file browser windows do not scale at all. While the popup file browser has a scale dial, it only scaled the folder/file list, not the default path list on the left, OK/Cacel buttons and current path string.

The above two issues make the plugin unusable with 4K monitors and painful to use even on 1080p. Check attached screenshots.
![1](https://github.com/brummer10/Fluida.lv2/assets/157605035/8bfd1bdf-de59-49f2-859d-39ea7e573ad0)
![2](https://github.com/brummer10/Fluida.lv2/assets/157605035/e205d6f6-a53c-44bd-9f68-1976ddf1ffb8)
![3](https://github.com/brummer10/Fluida.lv2/assets/157605035/d1674de2-6325-4844-940b-87a5d143638f)
![4](https://github.com/brummer10/Fluida.lv2/assets/157605035/f8d5ed96-2d7c-443a-a20c-a1dfb103ea51)

**Comment by brummer10** [comment]
Hi
Within the latest commit I fixed the combobox and the SF2 file path font size scaling issue. 
The Piano roll isn't meant to scale at all. But looking at your screen shots it seems I need to rethink that. 
Also the File Browser, the scale control is indeed only meant for the content, not for the window itself. 
I properly need some time to come up with a proper solution for that.

**Comment by brummer10** [comment]
Latest commit now implemented full Hdpi support. Means the GUI use the system dpi settings to scale itself before open. So now the Piano roll and the File Browser should come in correct size as well.

**Comment by onlyforanonemails** [comment]
I can verify as soon as a new binary is available.
