### ISSUE TITLE
trying to load a SFZ make it crashes

### ISSUE THREAD

**Issue by trebmuh** [brummer10/Fluida.lv2#3]
I've tested that it plays fine a SF2 and a SF3, and I've tried to load a SFZ (don't ask me why...).
Bang!

**Comment by brummer10** [comment]
Yes, that's to be expected.

**Comment by brummer10** [comment]
Okay, I've implemented a guard against that now. Still, we cant use sfz files, but it will now pop up a message to notify about that, instead crash, when you try that again.

**Comment by trebmuh** [comment]
Tested it from a116706 and it works perfectly (aka: no crash but the pop up is there).
Thank you very much.
