### ISSUE TITLE
Questions about Fluida

### ISSUE THREAD

**Issue by audio2000** [brummer10/Fluida.lv2#36]
I apologize to post this here but I am not sure where else to ask these questions.
I will try to put all the question I have in the post rather than a bunch of separate posts.

I will start out with these few questions.
1.) Are there plans to continue to update this plugin or is this plugin no longer in development?

2.) If still in development, are feature requests being considered for this plugin?

3.) Soundfont players appear to be used in two different ways.
-As a way to play/provide sounds when playing MIDI files using a GM style soundfont
-To use soundfonts as virtual instruments where the user can play/generate MIDI notes to "play" soundfonts
I was wondering what the use case is viewed as with a plugin like this?
Obviously this plugin can do both, but the reason I ask this question is because my feature requests will depend how this plugin is intended to be used.  No point in making requests if they are not inline with what the plugin is intended to be used for.
For example I would use this plugin for both use cases but in the context of being used as a virtual instrument player, I am looking for a plugin that provides access to more parameters (CC) that Fluidsynth makes available.
However there are no soundfont players in Linux currently that offer parameters other than the two effects that Fluidsynth provides.
I was wondering if other parameters (CCs) would be considered to be added to the plugin?

Thank you to anyone who takes the time to read this and for any answers provided

**Comment by brummer10** [comment]
Hi
Well it's the right place here.
There are no plans to stop development for this plugin, just, for me it does all I need, so there is no need to update.
Feature requests been welcome here.
The plug is meant to be used for both cases. 
Fluida forward any received MIDI CC message to fluidsynth, so you could use any CC message which fluidsynth could handle. See here:
 https://github.com/FluidSynth/fluidsynth/wiki/FluidFeatures#midi-control-change-implementation-chart

**Comment by audio2000** [comment]
@brummer10 
Thank you again for taking the time to respond to my questions.
Okay now that I know that this plugin is intended for both use cases, I will try to make two separate posts, one for each use case.
While I have you here I just want to say thank you in general for all the plugins you provide, so much great stuff.
I have noticed that there are a handful of developers that contribute huge amounts to the Linux audio community and your name is definitely on that list, I imagine your plugins / software helps out many users, so thank you.
