### ISSUE TITLE
Please use -Wl,--no-undefined linker flag

### ISSUE THREAD

**Issue by falkTX** [brummer10/Fluida.lv2#4]
Otherwise missing symbols are not detected, for example building here:
```
/home/falktx/.lv2/Fluida.lv2/Fluida.so: undefined symbol: fluid_audio_driver_register
```

My build of fluidsynth has the audio/midi drivers taken out, so they dont conflict ever with host stuff.

**Comment by brummer10** [comment]
Done, thanks for the hint.

**Comment by falkTX** [comment]
This is still missing from GUI_LDFLAGS

**Comment by brummer10** [comment]
Ups, indeed. Thanks for the hint, fixed now.
