### ISSUE TITLE
[Feature Request] Adding a separate patch window that can stay open 

### ISSUE THREAD

**Issue by audio2000** [brummer10/Fluida.lv2#40]
Unfortunately my "Using Fluida as an instrument" post did not seem to fly, so I will go to my second use.

In Fluida there is a "Channel Matrix" which opens up as a separate window.
If you keep that window open and you open or drag & drop soundfonts into the GUI, this "Channel Matrix" updates the channel drop downs based on the patches offered by that new soundfont.

Would it be considered to offer a very similar window to what is mentioned above, but have it be a "Bank/Patch" window?  It would function in the same way where this window can stay open and also would update the list based on if different soundfonts are added while this window is still open during that file opening.  Would be activated in GUI with an icon that toggles show/hide window exactly how the Channel Matrix button functions.

If interested in this idea, here are some more properties for this window.
-Could have a filter field at top or bottom (See #38 for ideas regarding this)
-Window could be resized
-Window size and placement saves/remembers (if possible)
-Patches could appear in a "List View" or "Details View" like file managers offer with columns: patch # / name can be clicked on to change sort.  Or if not, maybe can use "Compact View" instead where if the windows width is increased then shows two or more columns of the list continuing to the next column.
-Hotkeys
Allow Home / End / PageUp / PageDown / ArrowUp / ArrowDown to all be able to navigate through the list.  Would be a highlight cursor selecting files like a file manager does.
-The cursor highlight would either automatically load this patch into Fluida.

Because soundfonts can contain so many patches inside of them, this just allows user to be able to see more of what they contain.  Gives a visual because many times you open a soundfont and have no clue if it contains 1 patch or hundreds.  This also allows you to be able to go through patches more efficiently because you can be testing them with a MIDI keyboard as you move the cursor through the patch list.

Anyways I do not think this is going to probably be considered either but just feel that this could be helpful if anyone is interested.   There are really no programs/plugins in Linux that allow for testing out soundfonts in this way.

Thank you to anyone who reads this.

**Comment by brummer10** [comment]
It's just that I'm running out of time. I've currently no time left by my day job.
