### ISSUE TITLE
resets to first instrument when playing a loop in Reaper

### ISSUE THREAD

**Issue by j2l** [brummer10/Fluida.lv2#45]
Thank you for sharing this great project!
I use it in Reaper 6 on Ubuntu 22.04
As soon as it loops, it goes back to Celesta, the first instrument of Orchestral essentials sf2, even if it shows another one:
![image](https://github.com/user-attachments/assets/cc25b550-56ba-4c0b-bd6b-0e817570c7cb)

Any idea?

**Comment by brummer10** [comment]
Maybe you've a MIDI program change message at the beginning of your loop, the PC message could be it.

**Comment by j2l** [comment]
> MIDI program change message

Thank you! You're  totally right.
double click midi track > ALT+3 (select event list) > delete PC event
