### ISSUE TITLE
File browser cannot handle symlinks

### ISSUE THREAD

**Issue by falkTX** [brummer10/Fluida.lv2#5]
I have a `/Shared` symlink to some common useful files inside an external disk, fluida file browser cannot enter this folder, I am guessing because it is a symlink.
That makes it a bit painful, because then I have to to manually go to /media/falktx/.../Personal/...etcetc

**Comment by falkTX** [comment]
This is a bit worse than I thought.
I simply cant pick any file in my system.

I said incorrect things in the previous post, my `/Shared/` folder is not a symlink, but the mount point for a external XFS formatted drive.
fluida cannot enter it.
then, `/home/falktx/Personal/` IS the symlink. fluida cannot enter this one either.
Here is a video showing the issue https://falktx.com/data/carla-fluida-browser.mp4

Latest fluida master branch

**Comment by brummer10** [comment]
The issue was that I use d_type from dirent to check if content is a file or a directory. Some file systems didn't support that. 
I've fixed that now by using stat on entry's which return DT_UNKNOWN.
