### ISSUE TITLE
File browser window does not set transient hint

### ISSUE THREAD

**Issue by falkTX** [brummer10/Fluida.lv2#6]
If the host has the plugin GUI has "transient" to itself (that is, on top of the base host window), the file browser window can appear behind the host and plugin GUI, making it hard to find.
Please add the transient window id to the parent of the plugin UI (that is, the Window it embeds into), so Window managers can properly place/stack the window.

**Comment by brummer10** [comment]
The usual XSetTransientForHint() didn't work for embedded windows, so I need to use  XChangeProperty() and set _NET_WM_STATE_ABOVE.

**Comment by falkTX** [comment]
you cant set it for the embed window, but you have access to the host one, because the plugin embeds in it.
so you can set the transient hint to that

**Comment by brummer10** [comment]
I've tried that as well, but didn't get it to work. Set  _NET_WM_STATE_ABOVE works well here.
